### ISSUE TITLE
Can't enable: Encounted Exception! : Value was either too large or too small for an Int32.

### ISSUE THREAD

**Issue by SuperDOS** [Alby1987/BuzzMultiBuzzersPlugin#2]
USB_BMB:ErrorTrapper Critical: -2 : Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at HIDInterface.HIDDevice.getConnectedDevices()
   at BuzzPluginDriver.Buzzers.USBinit()
   at BMBUSB.USB_Buzzer..ctor(Int32 BuzzerNum)
   at BMBUSB.BMB_USB.CreateDevices()
   at BMBUSB.BMB_USB.Init()

**Comment by Alby1987** [comment]
Do this happen everytime you start PCSX2? Do have something else attached to USB?

**Comment by SuperDOS** [comment]
yes this happens every time you choose the plugin and press apply.
This computer I've tested with has USB mouse, keyboad, webcam and a focusrite 2i2.

**Comment by Alby1987** [comment]
If is not hard for you, may you try with only the mouse attached? It seems an error on the serialnumber enumerator. I programmed this in a laptop without any accessory attached, I think there is some sort of conflict with some of your device. If it is the case, I will try to recognize the serialnumber of only the Buzzers. Thank you!

**Comment by SuperDOS** [comment]
I tried to remove everything except the mouse and got the same error.
Remove the mouse and with just the keyboard connected it worked.
So it seems the mouse is causing the conflict in my case.

**Comment by Alby1987** [comment]
Perfect! I will try not to use the Serial Number during enumeration of USB devices outside the Buzzers scope :)

**Comment by SuperDOS** [comment]
great, give a shout when there's a new version to test. :)

**Comment by Alby1987** [comment]
@SuperDOS Would you like to test this release?
http://s000.tinyupload.com/index.php?file_id=36411943735650966930

Thank you :)

**Comment by SuperDOS** [comment]
@Alby1987 seems to be working just fine now! 👍

**Comment by Alby1987** [comment]
Perfect! Doing a real release just now! :)
