### ISSUE TITLE
Buzz Buzzers buttons not working once game is started

### ISSUE THREAD

**Issue by allgoodusernamesaretaken** [Alby1987/BuzzMultiBuzzersPlugin#3]
Hi, I installed your plugin on PCSX2 1.6.0, which is the only plugin to actually get my PS2 buzzers to work, which is great. This got the BUZZ Junior party (with the monkeys) to start. The config questions in the game do respond to the buzzer buttons, but when you need to choose a game mode, no buttons are working anymore. Is there a fix for this? I tried playing around with several settings to no avail. Thanks!

**Comment by Alby1987** [comment]
I don't have the game. Do you have wired or wireless buzzers?

**Comment by martimparente** [comment]
I had the exactly same problem, with both buzz Junior Party and buzz Junior Dino and solved by putting the configuration like this image on this plugin configuration and now the main menu part detects the buttons!

![Sem Título](https://user-images.githubusercontent.com/47867183/91583625-67b4ad80-e949-11ea-90dd-2a8de17436af.jpg)

**Comment by allgoodusernamesaretaken** [comment]
Thank you both for responding!
The buzzers are wired. I wil try Sharlimar's settings and report back if this worked in my case.

**Comment by allgoodusernamesaretaken** [comment]
I just tried Sharlimar's settings and this worked! Kids will be pleased, thank you!
