### ISSUE TITLE
USB_BMB:OHCI Error: 9 : Error: ohci_write: Bad offset 0x80 (32)

### ISSUE THREAD

**Issue by martimparente** [Alby1987/BuzzMultiBuzzersPlugin#4]
Hi Alby1987
First thank you for your plugin!

I need your help I'm getting this error and cant solved it

I tried in two laptops with no usb connect devices connected,  with PCSX2 1.60 and 1.40 and nothing...

I'll put here the log! The error message is:
"USB_BMB:OHCI Error: 9 : Error: ohci_write: Bad offset 0x80 (32)"

This appears when I load the game, and on screen it says to connect the buzzers...

Log Console:
[log.txt](https://github.com/Alby1987/BuzzMultiBuzzersPlugin/files/5076416/log.txt)

Thank you!

**Comment by Alby1987** [comment]
Do you have wired or wireless buzzers? What game was that?

**Comment by martimparente** [comment]
Wired ones and I used the 1.0.3 version
Tried aswell on my desktop and same error

I tried on with
buzz junior jungle (Europe)
buzz junior dino (Europe)
buzz! ¿Qué Sabes de tu País? (Europe)

**Comment by Alby1987** [comment]
I didn't test with Buzz Junior, and other people seems to have the same problem. About the National Quiz, I tested with italian version and it worked perfectly. Do you have the latest Windows 10?

**Comment by martimparente** [comment]
Yes latest windows 10
I put the log also if it can helps, it has my specs etc
Do you know what this error usually means?

**Comment by martimparente** [comment]
Gonna try on that buzz national italian quiz to see if it works

**Comment by martimparente** [comment]
Another info is that when I connect the USB buzzers it nevers blink the red buttons or anything
And on the Device Managers it appears as "Standard USB HUB" with the little yellow triangle with a "!", it says "the device is not properly working because Windows can't load the drivers needed (Code 31)"
Is this supposed to happend?

Thanks!

![Sem Título](https://user-images.githubusercontent.com/47867183/91480836-6fb61400-e89b-11ea-86a4-ce24cf782db7.png)

**Comment by Alby1987** [comment]
> Another info is that when I connect the USB buzzers it nevers blink the red buttons or anything
> And on the Device Managers it appears as "Standard USB HUB" with the little yellow triangle with a "!", it says "the device is not properly working because Windows can't load the drivers needed (Code 31)"
> Is this supposed to happend?
> 
> Thanks!
> 
> ![Sem Título](https://user-images.githubusercontent.com/47867183/91480836-6fb61400-e89b-11ea-86a4-ce24cf782db7.png)

That's pretty interesting! Buzzers are seen as Game controllers by Windows, in fact you can try them in the gamepad control panel as they were a gamepad. You can try to delete the yellow triangles driver, detach the buzzers, reboot and try again to plug them: Windows should install the generic drivers.

**Comment by martimparente** [comment]
Ok problem solved, it was the drivers...I found this on Steam foruns it solved the problem
Thanks for your time!

Solution:
"Some models are initially recognized by Windows as USB hubs. In that case open the Windows device manager and check for a device an unknown device (with the yellow warning triangle). Open the properties by rightclicking the device and then switch the driver:

1. Go the "Driver" tab
2. Click "Update Driver"
3. Select "Browse my computer for driver software"
4. Select "Let me pick from a list of available drivers on my computer"
5. Select "USB input device (HID)" and click 'Next' to configure the new driver

After this your Buzz! controller should be listed in the device list as mentioned above"
