### ISSUE TITLE
Encounted Exception

### ISSUE THREAD

**Issue by sephirem** [Alby1987/BuzzMultiBuzzersPlugin#6]
Encounted Excption! : Impossible
![Capture d’écran (1)](https://user-images.githubusercontent.com/77636634/104949977-21c3b900-59c0-11eb-9a6e-9cce47cb7ace.png)

**Comment by Alby1987** [comment]
Have you installed the plugin as specified? There should be a DLL in the plugin folder, and another one in the same level as ePSXe.exe executable

**Comment by sephirem** [comment]
Oooooooh sorry I haven't understood where to place the second DLL and I placed it in the wrong PCSX2. It works fine now. I'm really sorry for the waste of time and big thanks for the help !!
